package PdfServiceApp;


/**
* PdfServiceApp/_PdfServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PdfService.idl
* Saturday, May 9, 2026 7:04:06 PM GMT
*/

public class _PdfServiceStub extends org.omg.CORBA.portable.ObjectImpl implements PdfServiceApp.PdfService
{


  // Fusion de PDF
  public void fusion (String fichier1, String fichier2, org.omg.CORBA.StringHolder resultat)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("fusion", true);
                $out.write_string (fichier1);
                $out.write_string (fichier2);
                $in = _invoke ($out);
                resultat.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                fusion (fichier1, fichier2, resultat        );
            } finally {
                _releaseReply ($in);
            }
  } // fusion


  // Découpage de PDF
  public void decoupage (String fichier, int pageDebut, int pageFin, org.omg.CORBA.StringHolder resultat)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("decoupage", true);
                $out.write_string (fichier);
                $out.write_long (pageDebut);
                $out.write_long (pageFin);
                $in = _invoke ($out);
                resultat.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                decoupage (fichier, pageDebut, pageFin, resultat        );
            } finally {
                _releaseReply ($in);
            }
  } // decoupage


  // Extraction de pages
  public void extrairePages (String fichier, int pageDebut, int pageFin, org.omg.CORBA.StringHolder resultat)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extrairePages", true);
                $out.write_string (fichier);
                $out.write_long (pageDebut);
                $out.write_long (pageFin);
                $in = _invoke ($out);
                resultat.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                extrairePages (fichier, pageDebut, pageFin, resultat        );
            } finally {
                _releaseReply ($in);
            }
  } // extrairePages


  // Suppression de pages (utilise le type PagesSeq)
  public void supprimerPages (String fichier, int[] pages, org.omg.CORBA.StringHolder resultat)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("supprimerPages", true);
                $out.write_string (fichier);
                PdfServiceApp.PagesSeqHelper.write ($out, pages);
                $in = _invoke ($out);
                resultat.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                supprimerPages (fichier, pages, resultat        );
            } finally {
                _releaseReply ($in);
            }
  } // supprimerPages


  // Ajout de mot de passe
  public void ajouterMotDePasse (String fichier, String motDePasse, org.omg.CORBA.StringHolder resultat)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ajouterMotDePasse", true);
                $out.write_string (fichier);
                $out.write_string (motDePasse);
                $in = _invoke ($out);
                resultat.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                ajouterMotDePasse (fichier, motDePasse, resultat        );
            } finally {
                _releaseReply ($in);
            }
  } // ajouterMotDePasse


  // Conversion PDF  Image
  public void convertirEnImage (String fichier, org.omg.CORBA.StringHolder resultat)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("convertirEnImage", true);
                $out.write_string (fichier);
                $in = _invoke ($out);
                resultat.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                convertirEnImage (fichier, resultat        );
            } finally {
                _releaseReply ($in);
            }
  } // convertirEnImage


  // Extraction de texte
  public void extraireTexte (String fichier, org.omg.CORBA.StringHolder texte)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extraireTexte", true);
                $out.write_string (fichier);
                $in = _invoke ($out);
                texte.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                extraireTexte (fichier, texte        );
            } finally {
                _releaseReply ($in);
            }
  } // extraireTexte


  // Création de PDF
  public void creerPdf (String contenuTexte, org.omg.CORBA.StringHolder resultat)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("creerPdf", true);
                $out.write_string (contenuTexte);
                $in = _invoke ($out);
                resultat.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                creerPdf (contenuTexte, resultat        );
            } finally {
                _releaseReply ($in);
            }
  } // creerPdf

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PdfServiceApp/PdfService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "PdfServiceApp._PdfServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _PdfServiceStub
