package PdfServiceApp;


/**
* PdfServiceApp/PagesSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PdfService.idl
* Saturday, May 9, 2026 7:04:06 PM GMT
*/


// Définition dun type séquence pour les pages
public final class PagesSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public PagesSeqHolder ()
  {
  }

  public PagesSeqHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PdfServiceApp.PagesSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PdfServiceApp.PagesSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PdfServiceApp.PagesSeqHelper.type ();
  }

}
