package PdfServiceApp;


/**
* PdfServiceApp/PdfServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PdfService.idl
* Saturday, May 9, 2026 7:04:06 PM GMT
*/

public interface PdfServiceOperations 
{

  // Fusion de PDF
  void fusion (String fichier1, String fichier2, org.omg.CORBA.StringHolder resultat);

  // Découpage de PDF
  void decoupage (String fichier, int pageDebut, int pageFin, org.omg.CORBA.StringHolder resultat);

  // Extraction de pages
  void extrairePages (String fichier, int pageDebut, int pageFin, org.omg.CORBA.StringHolder resultat);

  // Suppression de pages (utilise le type PagesSeq)
  void supprimerPages (String fichier, int[] pages, org.omg.CORBA.StringHolder resultat);

  // Ajout de mot de passe
  void ajouterMotDePasse (String fichier, String motDePasse, org.omg.CORBA.StringHolder resultat);

  // Conversion PDF  Image
  void convertirEnImage (String fichier, org.omg.CORBA.StringHolder resultat);

  // Extraction de texte
  void extraireTexte (String fichier, org.omg.CORBA.StringHolder texte);

  // Création de PDF
  void creerPdf (String contenuTexte, org.omg.CORBA.StringHolder resultat);
} // interface PdfServiceOperations
