package PdfServiceApp;


/**
* PdfServiceApp/PdfServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PdfService.idl
* Saturday, May 9, 2026 7:04:06 PM GMT
*/

public abstract class PdfServicePOA extends org.omg.PortableServer.Servant
 implements PdfServiceApp.PdfServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("fusion", new java.lang.Integer (0));
    _methods.put ("decoupage", new java.lang.Integer (1));
    _methods.put ("extrairePages", new java.lang.Integer (2));
    _methods.put ("supprimerPages", new java.lang.Integer (3));
    _methods.put ("ajouterMotDePasse", new java.lang.Integer (4));
    _methods.put ("convertirEnImage", new java.lang.Integer (5));
    _methods.put ("extraireTexte", new java.lang.Integer (6));
    _methods.put ("creerPdf", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Fusion de PDF
       case 0:  // PdfServiceApp/PdfService/fusion
       {
         String fichier1 = in.read_string ();
         String fichier2 = in.read_string ();
         org.omg.CORBA.StringHolder resultat = new org.omg.CORBA.StringHolder ();
         this.fusion (fichier1, fichier2, resultat);
         out = $rh.createReply();
         out.write_string (resultat.value);
         break;
       }


  // Découpage de PDF
       case 1:  // PdfServiceApp/PdfService/decoupage
       {
         String fichier = in.read_string ();
         int pageDebut = in.read_long ();
         int pageFin = in.read_long ();
         org.omg.CORBA.StringHolder resultat = new org.omg.CORBA.StringHolder ();
         this.decoupage (fichier, pageDebut, pageFin, resultat);
         out = $rh.createReply();
         out.write_string (resultat.value);
         break;
       }


  // Extraction de pages
       case 2:  // PdfServiceApp/PdfService/extrairePages
       {
         String fichier = in.read_string ();
         int pageDebut = in.read_long ();
         int pageFin = in.read_long ();
         org.omg.CORBA.StringHolder resultat = new org.omg.CORBA.StringHolder ();
         this.extrairePages (fichier, pageDebut, pageFin, resultat);
         out = $rh.createReply();
         out.write_string (resultat.value);
         break;
       }


  // Suppression de pages (utilise le type PagesSeq)
       case 3:  // PdfServiceApp/PdfService/supprimerPages
       {
         String fichier = in.read_string ();
         int pages[] = PdfServiceApp.PagesSeqHelper.read (in);
         org.omg.CORBA.StringHolder resultat = new org.omg.CORBA.StringHolder ();
         this.supprimerPages (fichier, pages, resultat);
         out = $rh.createReply();
         out.write_string (resultat.value);
         break;
       }


  // Ajout de mot de passe
       case 4:  // PdfServiceApp/PdfService/ajouterMotDePasse
       {
         String fichier = in.read_string ();
         String motDePasse = in.read_string ();
         org.omg.CORBA.StringHolder resultat = new org.omg.CORBA.StringHolder ();
         this.ajouterMotDePasse (fichier, motDePasse, resultat);
         out = $rh.createReply();
         out.write_string (resultat.value);
         break;
       }


  // Conversion PDF  Image
       case 5:  // PdfServiceApp/PdfService/convertirEnImage
       {
         String fichier = in.read_string ();
         org.omg.CORBA.StringHolder resultat = new org.omg.CORBA.StringHolder ();
         this.convertirEnImage (fichier, resultat);
         out = $rh.createReply();
         out.write_string (resultat.value);
         break;
       }


  // Extraction de texte
       case 6:  // PdfServiceApp/PdfService/extraireTexte
       {
         String fichier = in.read_string ();
         org.omg.CORBA.StringHolder texte = new org.omg.CORBA.StringHolder ();
         this.extraireTexte (fichier, texte);
         out = $rh.createReply();
         out.write_string (texte.value);
         break;
       }


  // Création de PDF
       case 7:  // PdfServiceApp/PdfService/creerPdf
       {
         String contenuTexte = in.read_string ();
         org.omg.CORBA.StringHolder resultat = new org.omg.CORBA.StringHolder ();
         this.creerPdf (contenuTexte, resultat);
         out = $rh.createReply();
         out.write_string (resultat.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PdfServiceApp/PdfService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PdfService _this() 
  {
    return PdfServiceHelper.narrow(
    super._this_object());
  }

  public PdfService _this(org.omg.CORBA.ORB orb) 
  {
    return PdfServiceHelper.narrow(
    super._this_object(orb));
  }


} // class PdfServicePOA
