package PdfServiceApp;


/**
* PdfServiceApp/PdfService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PdfService.idl
* Saturday, May 9, 2026 7:04:06 PM GMT
*/

public interface PdfService extends PdfServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PdfService
