package PdfServiceApp;

/**
* PdfServiceApp/PdfServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PdfService.idl
* Saturday, May 9, 2026 7:04:06 PM GMT
*/

public final class PdfServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public PdfServiceApp.PdfService value = null;

  public PdfServiceHolder ()
  {
  }

  public PdfServiceHolder (PdfServiceApp.PdfService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PdfServiceApp.PdfServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PdfServiceApp.PdfServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PdfServiceApp.PdfServiceHelper.type ();
  }

}
