package PdfServiceApp;


/**
* PdfServiceApp/PdfServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PdfService.idl
* Saturday, May 9, 2026 7:04:06 PM GMT
*/

abstract public class PdfServiceHelper
{
  private static String  _id = "IDL:PdfServiceApp/PdfService:1.0";

  public static void insert (org.omg.CORBA.Any a, PdfServiceApp.PdfService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PdfServiceApp.PdfService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PdfServiceApp.PdfServiceHelper.id (), "PdfService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PdfServiceApp.PdfService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PdfServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PdfServiceApp.PdfService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PdfServiceApp.PdfService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PdfServiceApp.PdfService)
      return (PdfServiceApp.PdfService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PdfServiceApp._PdfServiceStub stub = new PdfServiceApp._PdfServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PdfServiceApp.PdfService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PdfServiceApp.PdfService)
      return (PdfServiceApp.PdfService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PdfServiceApp._PdfServiceStub stub = new PdfServiceApp._PdfServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
