package PdfServiceApp;


/**
* PdfServiceApp/PdfService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PdfService.idl
* Sunday, May 10, 2026 11:26:25 AM GMT
*/

public interface PdfService extends PdfServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PdfService
